groups:
    Admin:
    - example
mcmmo:
    enabled: true
    level-required: 250
    default-position: prefix
    default-format: '[#skill#]'
    skill-titles:
        Acrobatics: Ninja
        Archery: Marksman
        Axes: Viking
        Mining: Miner
        Excavation: Excavator
        Fishing: Angler
        Herbalism: Farmer
        Repair: Blacksmith
        Swords: Fencer
        Taming: Trainer
        Unarmed: Berserker
        Woodcutting: Lumberjack
deathtp:
    enabled: true
    default-position: prefix
    default-format: '[#title#]'
    kill-streak:
    - Murderer:5
    - Demolisher:10
    multi-kill:
    - Reaver:2
heroes:
    enabled: true
    default-position: prefix
    default-format: '[#class#]'