groups:
    Admin:
    - example
mcmmo:
    level-required: 250
    default-position: prefix
    default-format: '[#skill#]'
deathtp:
    default-position: prefix
    default-format: '[#title#]'
    kill-streak:
    - Murderer:5
    - Demolisher:10
    multi-kill:
    - Reaver:2