default:
    use-permissions: true
    format: '#prefix##color##player##suffix#'
    color-names-by-default: true
    default-name-color: white
    color-by-group:
    - example:BLUE
groups:
    Admin:
    - example
spout:
    format: '#prefix#\n#player##suffix#'
mcmmo:
    enabled: true
    broadcast: false
    level-required: 250
    default-position: prefix
    default-format: '[#skill#]'
    skill-titles:
        Acrobatics: Ninja
        Archery: Marksman
        Axes: Viking
        Mining: Miner
        Excavation: Excavator
        Fishing: Angler
        Herbalism: Farmer
        Repair: Blacksmith
        Swords: Fencer
        Taming: Trainer
        Unarmed: Berserker
        Woodcutting: Lumberjack
deathtp:
    enabled: true
    broadcast: false
    default-position: prefix
    default-format: '[#title#]'
    kill-streak:
    - Murderer:5
    - Demolisher:10
    multi-kill:
    - Reaver:2
heroes:
    enabled: true
    broadcast: false
    require-master: true
    default-position: prefix
    default-format: '[#class#]'